# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'dotenv'

default_platform(:android)

platform :android do
  before_all do
    Dotenv.load("../../.env")
  end

  desc "Submit "
  lane :upload_browserstack do
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      # file_path: "app/build/outputs/apk/release/app-release.apk"
      file_path: "AC_APK_PATH/app-release.apk"
    )   
  end
end
